import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster, toast } from 'sonner';
const inter = Inter({ subsets: ['latin'] });
import { ThemeProvider } from 'next-themes';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/b7d6826033.js" ></script>
      </head>
      <body className={inter.className}>
        <ThemeProvider attribute="class"> 
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
  
}
